# This is a basic workflow to help you get started with Actions

name: TEST

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.5
      - name: Install Dependences
        run: poetry install
      - name: Run migrate
        run: |
          poetry run python manage.py makemigrations
          poetry run python manage.py migrate
      - name: Run test
        run: poetry run python manage.py test
