name: Run Tests
on:
  push:
    paths-ignore:
      - translation/*
  pull_request:
    paths-ignore:
      - translation/*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.5
      - name: Install Dependences
        run: poetry install
      - name: Run migrate
        run: |
          poetry run python manage.py makemigrations
          poetry run python manage.py migrate
      - name: Run test
        run: poetry run python manage.py test
      - name: Lint
        run: poetry run flake8 --count --show-source --statistics apps MeetPlan manage.py

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
        with:
          args: "--check --exclude \"/migrations/\" apps MeetPlan"
